const { createClient } = require('@supabase/supabase-js');
const {
  handleCORS,
  createAuthMiddleware,
  createErrorResponse,
  createSuccessResponse
} = require('./utils/security');
const { withLogging } = require('./utils/logger');
const { Validator } = require('./utils/validator');
const { createSermonChildren } = require('./utils/createSermonChildren');
const { cleanupOrphanAudioUpload } = require('./utils/storageCleanup');
const { isOwnedObjectPath, objectPathFromUrl } = require('./utils/audioObjectPath');

exports.handler = withLogging('create-sermon', async (event, context) => {
  const logger = event.logger;

  // Handle CORS preflight
  const corsResponse = handleCORS(event);
  if (corsResponse) return corsResponse;

  if (event.httpMethod !== 'POST') {
    return createErrorResponse(new Error('Method Not Allowed'), 405);
  }

  // Apply authentication
  const authMiddleware = createAuthMiddleware();
  const authResponse = await authMiddleware(event);
  if (authResponse) {
    return authResponse;
  }

  try {
    const supabaseUrl = process.env.SUPABASE_URL;
    const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

    if (!supabaseUrl || !supabaseKey) {
      logger.error('Missing Supabase configuration');
      return createErrorResponse(new Error('Server configuration error'), 500);
    }

    const supabase = createClient(supabaseUrl, supabaseKey);
    const user = event.user;

    // Parse request body
    const body = JSON.parse(event.body || '{}');

    // Validate required fields
    const requiredFields = ['localId', 'title', 'date', 'serviceType', 'audioFileName'];
    for (const field of requiredFields) {
      if (!body[field]) {
        return createErrorResponse(new Error(`Missing required field: ${field}`), 400);
      }
    }

    // Prepare sermon data
    // These two are client-supplied and were previously stored verbatim. Both
    // are later handed to SERVICE-ROLE storage calls — delete-sermon removes
    // the object, jobs.js signs it for AssemblyAI — so a crafted path let one
    // account reach another's audio (TAB-84). Refuse rather than sanitize:
    // there is no safe rewriting of "someone else's object".
    const claimedPath = body.audioFilePath || body.audioFileName;
    if (claimedPath && !isOwnedObjectPath(claimedPath, user.id)) {
      logger.security('unauthorized_audio_path', {
        userId: user.id,
        claimedPath: String(claimedPath).slice(0, 120),
        ip: event.headers['x-forwarded-for']
      });
      return createErrorResponse(new Error('Access denied: audio path does not belong to you'), 403);
    }

    // A URL that is not a recognizable sermon-audio object is refused rather
    // than stored unchecked: objectPathFromUrl returning null previously meant
    // "skip validation", so any attacker-controlled URL passed straight into a
    // column that is handed back to every client.
    const claimedUrlPath = body.audioFileUrl ? objectPathFromUrl(body.audioFileUrl) : null;
    if (body.audioFileUrl && !claimedUrlPath) {
      logger.security('unrecognized_audio_url', {
        userId: user.id,
        claimedUrl: String(body.audioFileUrl).slice(0, 120),
        ip: event.headers['x-forwarded-for']
      });
      return createErrorResponse(new Error('Invalid audio URL'), 400);
    }
    if (claimedUrlPath && !isOwnedObjectPath(claimedUrlPath, user.id)) {
      logger.security('unauthorized_audio_url', {
        userId: user.id,
        claimedPath: claimedUrlPath.slice(0, 120),
        ip: event.headers['x-forwarded-for']
      });
      return createErrorResponse(new Error('Access denied: audio URL does not belong to you'), 403);
    }

    const sermonData = {
      // Note: id field will be auto-generated by database DEFAULT gen_random_uuid()
      local_id: body.localId,
      user_id: user.id,
      title: body.title,
      date: body.date,
      service_type: body.serviceType,
      speaker: body.speaker || null,
      audio_file_name: body.audioFileName,
      audio_file_url: body.audioFileUrl || null,
      audio_file_size_bytes: body.audioFileSizeBytes || null,
      audio_file_path: body.audioFilePath || body.audioFileName,
      duration: body.duration || 0,
      transcription_status: body.transcriptionStatus || 'pending',
      summary_status: body.summaryStatus || 'pending',
      is_archived: body.isArchived || false,
      sync_status: 'synced',
      created_at: new Date().toISOString(),
      updated_at: body.updatedAt || new Date().toISOString()
    };

    logger.info('Creating sermon', {
      userId: user.id,
      localId: body.localId,
      title: body.title
    });

    // Insert sermon into database
    const { data: sermon, error: insertError } = await supabase
      .from('sermons')
      .insert(sermonData)
      .select()
      .single();

    if (insertError) {
      logger.error('Failed to create sermon', {
        error: insertError.message,
        code: insertError.code
      });

      // The row doesn't exist, so the audio uploaded for this attempt is
      // orphaned — remove it before reporting the failure (TAB-34). The
      // helper validates the path is the user's own and unreferenced.
      await cleanupOrphanAudioUpload({
        supabase,
        audioFilePath: sermonData.audio_file_path,
        userId: user.id,
        logger
      });

      // Handle unique constraint violation (sermon already exists)
      if (insertError.code === '23505') {
        return createErrorResponse(new Error('Sermon with this ID already exists'), 409);
      }

      return createErrorResponse(new Error(insertError.message), 500);
    }

    // Create related records if provided. Failed scopes are reported back so
    // the client keeps them dirty and re-pushes via update-sermon (TAB-34).
    const syncedScopes = await createSermonChildren({
      supabase,
      body,
      sermonId: sermon.id,
      userId: user.id,
      logger
    });

    if (!syncedScopes.notes || !syncedScopes.transcript || !syncedScopes.summary) {
      logger.warn('Sermon created with partial child inserts', {
        userId: user.id,
        sermonId: sermon.id,
        syncedScopes
      });
    } else {
      logger.info('Sermon created successfully', {
        userId: user.id,
        sermonId: sermon.id,
        remoteId: sermon.id
      });
    }

    return createSuccessResponse({
      id: sermon.id,
      localId: sermon.local_id,
      createdAt: sermon.created_at,
      updatedAt: sermon.updated_at,
      syncedScopes
    }, 201);

  } catch (error) {
    logger.error('Sermon creation failed', {
      userId: event.user?.id,
      error: error.message,
      stack: error.stack
    });
    return createErrorResponse(error, 500);
  }
});
