const { createClient } = require('@supabase/supabase-js');
const {
  handleCORS,
  createAuthMiddleware,
  createErrorResponse,
  createSuccessResponse
} = require('./utils/security');
const { withLogging } = require('./utils/logger');
const { Validator } = require('./utils/validator');
const { createSermonChildren } = require('./utils/createSermonChildren');

/**
 * Removes the audio object the client uploaded for this create attempt.
 * Upload paths are unique per attempt (generate-upload-url uses randomUUID),
 * so when the sermon row insert fails the object is unreachable garbage —
 * including on 409, where the existing row references its own earlier path.
 */
async function cleanupUploadedAudio(supabase, audioFilePath, logger) {
  if (!audioFilePath) return;

  try {
    const { error } = await supabase
      .storage
      .from('sermon-audio')
      .remove([audioFilePath]);

    if (error) {
      logger.warn('Failed to clean up orphan audio upload', {
        audioFilePath,
        error: error.message
      });
    } else {
      logger.info('Cleaned up orphan audio upload', { audioFilePath });
    }
  } catch (cleanupError) {
    logger.warn('Error cleaning up orphan audio upload', {
      audioFilePath,
      error: cleanupError.message
    });
  }
}

exports.handler = withLogging('create-sermon', async (event, context) => {
  const logger = event.logger;

  // Handle CORS preflight
  const corsResponse = handleCORS(event);
  if (corsResponse) return corsResponse;

  if (event.httpMethod !== 'POST') {
    return createErrorResponse(new Error('Method Not Allowed'), 405);
  }

  // Apply authentication
  const authMiddleware = createAuthMiddleware();
  const authResponse = await authMiddleware(event);
  if (authResponse) {
    return authResponse;
  }

  try {
    const supabaseUrl = process.env.SUPABASE_URL;
    const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

    if (!supabaseUrl || !supabaseKey) {
      logger.error('Missing Supabase configuration');
      return createErrorResponse(new Error('Server configuration error'), 500);
    }

    const supabase = createClient(supabaseUrl, supabaseKey);
    const user = event.user;

    // Parse request body
    const body = JSON.parse(event.body || '{}');

    // Validate required fields
    const requiredFields = ['localId', 'title', 'date', 'serviceType', 'audioFileName'];
    for (const field of requiredFields) {
      if (!body[field]) {
        return createErrorResponse(new Error(`Missing required field: ${field}`), 400);
      }
    }

    // Prepare sermon data
    const sermonData = {
      // Note: id field will be auto-generated by database DEFAULT gen_random_uuid()
      local_id: body.localId,
      user_id: user.id,
      title: body.title,
      date: body.date,
      service_type: body.serviceType,
      speaker: body.speaker || null,
      audio_file_name: body.audioFileName,
      audio_file_url: body.audioFileUrl || null,
      audio_file_size_bytes: body.audioFileSizeBytes || null,
      audio_file_path: body.audioFilePath || body.audioFileName,
      duration: body.duration || 0,
      transcription_status: body.transcriptionStatus || 'pending',
      summary_status: body.summaryStatus || 'pending',
      is_archived: body.isArchived || false,
      sync_status: 'synced',
      created_at: new Date().toISOString(),
      updated_at: body.updatedAt || new Date().toISOString()
    };

    logger.info('Creating sermon', {
      userId: user.id,
      localId: body.localId,
      title: body.title
    });

    // Insert sermon into database
    const { data: sermon, error: insertError } = await supabase
      .from('sermons')
      .insert(sermonData)
      .select()
      .single();

    if (insertError) {
      logger.error('Failed to create sermon', {
        error: insertError.message,
        code: insertError.code
      });

      // The row doesn't exist, so the audio uploaded for this attempt is
      // orphaned — remove it before reporting the failure (TAB-34).
      await cleanupUploadedAudio(supabase, sermonData.audio_file_path, logger);

      // Handle unique constraint violation (sermon already exists)
      if (insertError.code === '23505') {
        return createErrorResponse(new Error('Sermon with this ID already exists'), 409);
      }

      return createErrorResponse(new Error(insertError.message), 500);
    }

    // Create related records if provided. Failed scopes are reported back so
    // the client keeps them dirty and re-pushes via update-sermon (TAB-34).
    const syncedScopes = await createSermonChildren({
      supabase,
      body,
      sermonId: sermon.id,
      userId: user.id,
      logger
    });

    if (!syncedScopes.notes || !syncedScopes.transcript || !syncedScopes.summary) {
      logger.warn('Sermon created with partial child inserts', {
        userId: user.id,
        sermonId: sermon.id,
        syncedScopes
      });
    } else {
      logger.info('Sermon created successfully', {
        userId: user.id,
        sermonId: sermon.id,
        remoteId: sermon.id
      });
    }

    return createSuccessResponse({
      id: sermon.id,
      localId: sermon.local_id,
      createdAt: sermon.created_at,
      updatedAt: sermon.updated_at,
      syncedScopes
    }, 201);

  } catch (error) {
    logger.error('Sermon creation failed', {
      userId: event.user?.id,
      error: error.message,
      stack: error.stack
    });
    return createErrorResponse(error, 500);
  }
});
