import SwiftUI

// MARK: - Clickable Scripture Text

struct ClickableScriptureText: View {
    let text: String
    let font: Font
    let lineSpacing: CGFloat
    @StateObject private var scriptureAnalyzer = ScriptureAnalysisService()
    @State private var detectedReferences: [ScriptureReference] = []

    init(text: String, font: Font = .system(size: 16, design: .serif), lineSpacing: CGFloat = 7) {
        self.text = text
        self.font = font
        self.lineSpacing = lineSpacing
    }

    var body: some View {
        VStack(alignment: .leading, spacing: 14) {
            Text(createAttributedText())
                .font(font)
                .lineSpacing(lineSpacing)
                .foregroundStyle(Color.SV.onSurface)
                .textSelection(.enabled)

            if !detectedReferences.isEmpty {
                VStack(alignment: .leading, spacing: 8) {
                    Text("SCRIPTURE REFERENCES")
                        .font(.system(size: 10, weight: .medium))
                        .tracking(1.5)
                        .foregroundStyle(Color.SV.onSurface.opacity(0.4))

                    LazyVGrid(
                        columns: [GridItem(.adaptive(minimum: 110))],
                        alignment: .leading,
                        spacing: 6
                    ) {
                        ForEach(detectedReferences) { reference in
                            ScriptureReferenceButton(reference: reference)
                        }
                    }
                }
                .padding(.top, 4)
            }
        }
        .onAppear { analyzeReferences() }
        .onChange(of: text) { _, _ in analyzeReferences() }
    }

    private func createAttributedText() -> AttributedString {
        var string = AttributedString(text)
        for reference in detectedReferences {
            if let range = string.range(of: reference.raw) {
                string[range].foregroundColor = UIColor(Color.SV.primary)
                string[range].underlineStyle = .single
                string[range].underlineColor = UIColor(Color.SV.primary.opacity(0.4))
            }
        }
        return string
    }

    private func analyzeReferences() {
        detectedReferences = scriptureAnalyzer.analyzeScriptureReferences(in: text)
    }
}

// MARK: - Summary Text View

struct SummaryTextView: View {
    let summaryText: String
    let serviceType: String

    var body: some View {
        VStack(alignment: .leading, spacing: 0) {
            // Minimal share action, right-aligned
            HStack {
                Spacer()
                Button { shareSummary() } label: {
                    Image(systemName: "square.and.arrow.up")
                        .font(.system(size: 15, weight: .light))
                        .foregroundStyle(Color.SV.onSurface.opacity(0.35))
                }
                .buttonStyle(.plain)
            }
            .padding(.bottom, 20)

            StructuredSummaryView(summaryText: summaryText)
        }
    }

    private func shareSummary() {
        let shareText = """
        AI Summary — \(serviceType)

        \(summaryText)

        Generated by TabletNotes
        """

        if let windowScene = UIApplication.shared.connectedScenes.first as? UIWindowScene,
           let window = windowScene.windows.first,
           let rootVC = window.rootViewController {
            let activityVC = UIActivityViewController(activityItems: [shareText], applicationActivities: nil)
            if let popover = activityVC.popoverPresentationController {
                let bounds = window.bounds
                let validBounds = bounds.width > 0 && bounds.height > 0
                    && bounds.width.isFinite && bounds.height.isFinite
                if validBounds {
                    popover.sourceView = window
                    popover.sourceRect = CGRect(x: bounds.midX, y: bounds.midY, width: 0, height: 0)
                } else {
                    popover.sourceView = rootVC.view
                    popover.sourceRect = CGRect(x: 400, y: 400, width: 0, height: 0)
                }
                popover.permittedArrowDirections = []
            }
            rootVC.present(activityVC, animated: true)
        }
    }
}

// MARK: - Structured Summary View

struct StructuredSummaryView: View {
    let summaryText: String

    var body: some View {
        VStack(alignment: .leading, spacing: 32) {
            if summaryText.contains("**") {
                let sections = parseSimpleSections(summaryText)
                ForEach(Array(sections.enumerated()), id: \.element.title) { _, section in
                    svSection(title: section.title, content: section.content)
                }
            } else {
                ClickableScriptureText(text: summaryText)
            }
        }
    }

    @ViewBuilder
    private func svSection(title: String, content: String) -> some View {
        VStack(alignment: .leading, spacing: 10) {
            // Small caps section label
            Text(title.uppercased())
                .font(.system(size: 10, weight: .medium))
                .tracking(1.5)
                .foregroundStyle(Color.SV.onSurface.opacity(0.4))

            if isScriptureSection(title) {
                // Left-border block quote for scripture sections
                HStack(alignment: .top, spacing: 14) {
                    Rectangle()
                        .fill(Color.SV.primary.opacity(0.25))
                        .frame(width: 2)
                    ClickableScriptureText(
                        text: content,
                        font: .system(size: 15, design: .serif),
                        lineSpacing: 6
                    )
                }
                .padding(.leading, 4)
            } else {
                ClickableScriptureText(text: content)
            }
        }
    }

    private func isScriptureSection(_ title: String) -> Bool {
        let lower = title.lowercased()
        return lower.contains("scripture") || lower.contains("bible") || lower.contains("references")
    }

    private func parseSimpleSections(_ text: String) -> [(title: String, content: String)] {
        var sections: [(title: String, content: String)] = []
        let lines = text.components(separatedBy: .newlines)
        var currentTitle: String? = nil
        var currentContent: [String] = []

        for line in lines {
            let trimmed = line.trimmingCharacters(in: .whitespaces)
            if trimmed.hasPrefix("**") && trimmed.hasSuffix("**") && trimmed.count > 4 {
                if let title = currentTitle {
                    sections.append((title: title, content: currentContent.joined(separator: "\n")))
                }
                currentTitle = String(trimmed.dropFirst(2).dropLast(2))
                currentContent = []
            } else if !trimmed.isEmpty {
                currentContent.append(trimmed)
            }
        }

        if let title = currentTitle, !currentContent.isEmpty {
            sections.append((title: title, content: currentContent.joined(separator: "\n")))
        }

        return sections
    }
}

// MARK: - Preview

#Preview {
    ScrollView {
        SummaryTextView(
            summaryText: """
            **Main Scripture Text**
            John 3:16 — "For God so loved the world that he gave his one and only Son, that whoever believes in him shall not perish but have eternal life."

            **Brief Summary**
            In this sermon, we explored the profound truth of God's love for humanity through John 3:16. The message emphasized that salvation comes through faith alone, and we examined how this truth transforms our daily lives and relationship with God.

            **Key Points**
            - God's love is universal and sacrificial
            - Salvation is a gift received through faith, not works
            - Eternal life begins the moment we believe
            - Our response should be gratitude and transformed living

            **Memorable Elements**
            "God didn't just love the world — He gave His very best for the world's very worst."
            Like a father giving his life for his child, God's love goes beyond human comprehension.

            **Scripture References**
            John 3:16
            Ephesians 2:8-9
            Romans 8:28
            1 John 4:19
            """,
            serviceType: "Sunday Service"
        )
        .padding(24)
    }
    .background(Color.SV.surface)
}
